{
    "name": "Sale Offline App",
    "version": "19.0.1.0.0",
    "category": "Sales",
    "summary": "Installable offline app for field sales (proof of concept)",
    "author": "ADHOC SA",
    "website": "www.adhoc.com.ar",
    "license": "AGPL-3",
    "depends": [
        "sale",
        "account",
        "barcodes",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "data/ir_cron.xml",
        "data/mail_activity_type.xml",
        "views/sale_offline_order_views.xml",
        "views/sale_order_views.xml",
        "views/res_users_views.xml",
        "wizards/res_users_offline_pin_wizard_views.xml",
        "views/templates.xml",
    ],
    "assets": {
        # Same lean base as point_of_sale.base_app: web core without the backend webclient.
        "sale_offline_app.assets": [
            ("include", "web._assets_helpers"),
            ("include", "web._assets_backend_helpers"),
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            ("include", "web._assets_bootstrap_backend"),
            ("include", "web._assets_core"),
            ("remove", "web/static/src/core/browser/router.js"),
            ("remove", "web/static/src/core/debug/**/*"),
            "web/static/src/libs/fontawesome/css/font-awesome.css",
            "web/static/lib/odoo_ui_icons/*",
            "barcodes/static/src/barcode_service.js",
            "account/static/src/helpers/account_tax.js",
            "sale_offline_app/static/src/app/**/*",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": False,
}
